/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 70
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 63
#define ALIAS_COUNT 0
#define TOKEN_COUNT 39
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_newline_token1 = 1,
  anon_sym_POUND = 2,
  aux_sym_comment_token1 = 3,
  anon_sym_LBRACK = 4,
  anon_sym_meta = 5,
  anon_sym_RBRACK = 6,
  anon_sym_vars = 7,
  anon_sym_request = 8,
  anon_sym_DOT = 9,
  anon_sym_headers = 10,
  anon_sym_body = 11,
  anon_sym_assert = 12,
  anon_sym_script = 13,
  anon_sym_EQ = 14,
  anon_sym_exists = 15,
  anon_sym_contains = 16,
  anon_sym_matches = 17,
  anon_sym_LT = 18,
  anon_sym_GT = 19,
  sym_duration_value = 20,
  sym_raw_value = 21,
  anon_sym_GET = 22,
  anon_sym_POST = 23,
  anon_sym_PUT = 24,
  anon_sym_PATCH = 25,
  anon_sym_DELETE = 26,
  anon_sym_HEAD = 27,
  anon_sym_OPTIONS = 28,
  sym_key = 29,
  sym_text_fragment = 30,
  anon_sym_DQUOTE = 31,
  sym_string_content = 32,
  anon_sym_DQUOTE_DQUOTE_DQUOTE = 33,
  sym_body_text = 34,
  anon_sym_COMMA = 35,
  anon_sym_LBRACE_LBRACE = 36,
  aux_sym_variable_ref_token1 = 37,
  anon_sym_RBRACE_RBRACE = 38,
  sym_source_file = 39,
  sym_newline = 40,
  sym_comment = 41,
  sym_shorthand_request = 42,
  sym_section_header = 43,
  sym_pair = 44,
  sym_assertion_exists = 45,
  sym_assertion_contains = 46,
  sym_assertion_matches = 47,
  sym_assertion_lt = 48,
  sym_assertion_gt = 49,
  sym_assertion_value = 50,
  sym_http_method = 51,
  sym_value = 52,
  sym_quoted_string = 53,
  sym_triple_quoted_string = 54,
  sym_body_content = 55,
  sym_array_value = 56,
  sym_variable_ref = 57,
  aux_sym_source_file_repeat1 = 58,
  aux_sym_value_repeat1 = 59,
  aux_sym_quoted_string_repeat1 = 60,
  aux_sym_body_content_repeat1 = 61,
  aux_sym_array_value_repeat1 = 62,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_newline_token1] = "newline_token1",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_LBRACK] = "[",
  [anon_sym_meta] = "meta",
  [anon_sym_RBRACK] = "]",
  [anon_sym_vars] = "vars",
  [anon_sym_request] = "request",
  [anon_sym_DOT] = ".",
  [anon_sym_headers] = "headers",
  [anon_sym_body] = "body",
  [anon_sym_assert] = "assert",
  [anon_sym_script] = "script",
  [anon_sym_EQ] = "=",
  [anon_sym_exists] = "exists",
  [anon_sym_contains] = "contains",
  [anon_sym_matches] = "matches",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [sym_duration_value] = "duration_value",
  [sym_raw_value] = "raw_value",
  [anon_sym_GET] = "GET",
  [anon_sym_POST] = "POST",
  [anon_sym_PUT] = "PUT",
  [anon_sym_PATCH] = "PATCH",
  [anon_sym_DELETE] = "DELETE",
  [anon_sym_HEAD] = "HEAD",
  [anon_sym_OPTIONS] = "OPTIONS",
  [sym_key] = "key",
  [sym_text_fragment] = "text_fragment",
  [anon_sym_DQUOTE] = "\"",
  [sym_string_content] = "string_content",
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = "\"\"\"",
  [sym_body_text] = "body_text",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [aux_sym_variable_ref_token1] = "variable_ref_token1",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [sym_source_file] = "source_file",
  [sym_newline] = "newline",
  [sym_comment] = "comment",
  [sym_shorthand_request] = "shorthand_request",
  [sym_section_header] = "section_header",
  [sym_pair] = "pair",
  [sym_assertion_exists] = "assertion_exists",
  [sym_assertion_contains] = "assertion_contains",
  [sym_assertion_matches] = "assertion_matches",
  [sym_assertion_lt] = "assertion_lt",
  [sym_assertion_gt] = "assertion_gt",
  [sym_assertion_value] = "assertion_value",
  [sym_http_method] = "http_method",
  [sym_value] = "value",
  [sym_quoted_string] = "quoted_string",
  [sym_triple_quoted_string] = "triple_quoted_string",
  [sym_body_content] = "body_content",
  [sym_array_value] = "array_value",
  [sym_variable_ref] = "variable_ref",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_value_repeat1] = "value_repeat1",
  [aux_sym_quoted_string_repeat1] = "quoted_string_repeat1",
  [aux_sym_body_content_repeat1] = "body_content_repeat1",
  [aux_sym_array_value_repeat1] = "array_value_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_newline_token1] = aux_sym_newline_token1,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_meta] = anon_sym_meta,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_vars] = anon_sym_vars,
  [anon_sym_request] = anon_sym_request,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_headers] = anon_sym_headers,
  [anon_sym_body] = anon_sym_body,
  [anon_sym_assert] = anon_sym_assert,
  [anon_sym_script] = anon_sym_script,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_exists] = anon_sym_exists,
  [anon_sym_contains] = anon_sym_contains,
  [anon_sym_matches] = anon_sym_matches,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [sym_duration_value] = sym_duration_value,
  [sym_raw_value] = sym_raw_value,
  [anon_sym_GET] = anon_sym_GET,
  [anon_sym_POST] = anon_sym_POST,
  [anon_sym_PUT] = anon_sym_PUT,
  [anon_sym_PATCH] = anon_sym_PATCH,
  [anon_sym_DELETE] = anon_sym_DELETE,
  [anon_sym_HEAD] = anon_sym_HEAD,
  [anon_sym_OPTIONS] = anon_sym_OPTIONS,
  [sym_key] = sym_key,
  [sym_text_fragment] = sym_text_fragment,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_string_content] = sym_string_content,
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = anon_sym_DQUOTE_DQUOTE_DQUOTE,
  [sym_body_text] = sym_body_text,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [aux_sym_variable_ref_token1] = aux_sym_variable_ref_token1,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [sym_source_file] = sym_source_file,
  [sym_newline] = sym_newline,
  [sym_comment] = sym_comment,
  [sym_shorthand_request] = sym_shorthand_request,
  [sym_section_header] = sym_section_header,
  [sym_pair] = sym_pair,
  [sym_assertion_exists] = sym_assertion_exists,
  [sym_assertion_contains] = sym_assertion_contains,
  [sym_assertion_matches] = sym_assertion_matches,
  [sym_assertion_lt] = sym_assertion_lt,
  [sym_assertion_gt] = sym_assertion_gt,
  [sym_assertion_value] = sym_assertion_value,
  [sym_http_method] = sym_http_method,
  [sym_value] = sym_value,
  [sym_quoted_string] = sym_quoted_string,
  [sym_triple_quoted_string] = sym_triple_quoted_string,
  [sym_body_content] = sym_body_content,
  [sym_array_value] = sym_array_value,
  [sym_variable_ref] = sym_variable_ref,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_value_repeat1] = aux_sym_value_repeat1,
  [aux_sym_quoted_string_repeat1] = aux_sym_quoted_string_repeat1,
  [aux_sym_body_content_repeat1] = aux_sym_body_content_repeat1,
  [aux_sym_array_value_repeat1] = aux_sym_array_value_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_newline_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_meta] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_vars] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_request] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_headers] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_body] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_assert] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_script] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_exists] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_contains] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_matches] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_duration_value] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_GET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POST] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PUT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PATCH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DELETE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_HEAD] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_OPTIONS] = {
    .visible = true,
    .named = false,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [sym_text_fragment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_body_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_variable_ref_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_shorthand_request] = {
    .visible = true,
    .named = true,
  },
  [sym_section_header] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_assertion_exists] = {
    .visible = true,
    .named = true,
  },
  [sym_assertion_contains] = {
    .visible = true,
    .named = true,
  },
  [sym_assertion_matches] = {
    .visible = true,
    .named = true,
  },
  [sym_assertion_lt] = {
    .visible = true,
    .named = true,
  },
  [sym_assertion_gt] = {
    .visible = true,
    .named = true,
  },
  [sym_assertion_value] = {
    .visible = true,
    .named = true,
  },
  [sym_http_method] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_triple_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_body_content] = {
    .visible = true,
    .named = true,
  },
  [sym_array_value] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_ref] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_value_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_value_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 7,
  [10] = 6,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 8,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 38,
  [44] = 39,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 8,
  [50] = 50,
  [51] = 8,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 57,
  [65] = 57,
  [66] = 57,
  [67] = 60,
  [68] = 60,
  [69] = 60,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(89);
      ADVANCE_MAP(
        '\n', 90,
        '\r', 1,
        '"', 190,
        '#', 91,
        ',', 203,
        '.', 101,
        '<', 110,
        '=', 106,
        '>', 111,
        'D', 15,
        'G', 16,
        'H', 17,
        'O', 25,
        'P', 12,
        '[', 95,
        ']', 98,
        'a', 70,
        'b', 56,
        'c', 57,
        'e', 82,
        'h', 44,
        'm', 34,
        'r', 43,
        's', 39,
        'v', 37,
        '{', 84,
        '}', 85,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(53);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(90);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(197);
      END_STATE();
    case 3:
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '"') ADVANCE(200);
      if (lookahead == '{') ADVANCE(201);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(198);
      if (lookahead == '\n' ||
          lookahead == '}') ADVANCE(197);
      if (lookahead != 0) ADVANCE(202);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(195);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(189);
      if (lookahead == '[') ADVANCE(96);
      if (lookahead == '{') ADVANCE(84);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(6);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(188);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(189);
      if (lookahead == '\\') ADVANCE(86);
      if (lookahead == '{') ADVANCE(84);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(193);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '}') ADVANCE(194);
      END_STATE();
    case 8:
      if (lookahead == '"') ADVANCE(189);
      if (lookahead == ']') ADVANCE(98);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(206);
      END_STATE();
    case 9:
      if (lookahead == '"') ADVANCE(189);
      if (lookahead == '{') ADVANCE(84);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(9);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(188);
      END_STATE();
    case 10:
      if (lookahead == '"') ADVANCE(191);
      if (lookahead == '{') ADVANCE(117);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(114);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(115);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(118);
      END_STATE();
    case 11:
      if (lookahead == 'A') ADVANCE(14);
      END_STATE();
    case 12:
      if (lookahead == 'A') ADVANCE(30);
      if (lookahead == 'O') ADVANCE(27);
      if (lookahead == 'U') ADVANCE(31);
      END_STATE();
    case 13:
      if (lookahead == 'C') ADVANCE(20);
      END_STATE();
    case 14:
      if (lookahead == 'D') ADVANCE(134);
      END_STATE();
    case 15:
      if (lookahead == 'E') ADVANCE(22);
      END_STATE();
    case 16:
      if (lookahead == 'E') ADVANCE(28);
      END_STATE();
    case 17:
      if (lookahead == 'E') ADVANCE(11);
      END_STATE();
    case 18:
      if (lookahead == 'E') ADVANCE(131);
      END_STATE();
    case 19:
      if (lookahead == 'E') ADVANCE(33);
      END_STATE();
    case 20:
      if (lookahead == 'H') ADVANCE(128);
      END_STATE();
    case 21:
      if (lookahead == 'I') ADVANCE(24);
      END_STATE();
    case 22:
      if (lookahead == 'L') ADVANCE(19);
      END_STATE();
    case 23:
      if (lookahead == 'N') ADVANCE(26);
      END_STATE();
    case 24:
      if (lookahead == 'O') ADVANCE(23);
      END_STATE();
    case 25:
      if (lookahead == 'P') ADVANCE(29);
      END_STATE();
    case 26:
      if (lookahead == 'S') ADVANCE(137);
      END_STATE();
    case 27:
      if (lookahead == 'S') ADVANCE(32);
      END_STATE();
    case 28:
      if (lookahead == 'T') ADVANCE(119);
      END_STATE();
    case 29:
      if (lookahead == 'T') ADVANCE(21);
      END_STATE();
    case 30:
      if (lookahead == 'T') ADVANCE(13);
      END_STATE();
    case 31:
      if (lookahead == 'T') ADVANCE(125);
      END_STATE();
    case 32:
      if (lookahead == 'T') ADVANCE(122);
      END_STATE();
    case 33:
      if (lookahead == 'T') ADVANCE(18);
      END_STATE();
    case 34:
      if (lookahead == 'a') ADVANCE(77);
      if (lookahead == 'e') ADVANCE(78);
      END_STATE();
    case 35:
      if (lookahead == 'a') ADVANCE(97);
      END_STATE();
    case 36:
      if (lookahead == 'a') ADVANCE(42);
      END_STATE();
    case 37:
      if (lookahead == 'a') ADVANCE(62);
      END_STATE();
    case 38:
      if (lookahead == 'a') ADVANCE(51);
      END_STATE();
    case 39:
      if (lookahead == 'c') ADVANCE(60);
      END_STATE();
    case 40:
      if (lookahead == 'c') ADVANCE(49);
      END_STATE();
    case 41:
      if (lookahead == 'd') ADVANCE(83);
      END_STATE();
    case 42:
      if (lookahead == 'd') ADVANCE(48);
      END_STATE();
    case 43:
      if (lookahead == 'e') ADVANCE(59);
      END_STATE();
    case 44:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 45:
      if (lookahead == 'e') ADVANCE(61);
      END_STATE();
    case 46:
      if (lookahead == 'e') ADVANCE(73);
      END_STATE();
    case 47:
      if (lookahead == 'e') ADVANCE(68);
      END_STATE();
    case 48:
      if (lookahead == 'e') ADVANCE(63);
      END_STATE();
    case 49:
      if (lookahead == 'h') ADVANCE(47);
      END_STATE();
    case 50:
      if (lookahead == 'i') ADVANCE(58);
      END_STATE();
    case 51:
      if (lookahead == 'i') ADVANCE(54);
      END_STATE();
    case 52:
      if (lookahead == 'i') ADVANCE(72);
      END_STATE();
    case 53:
      if (lookahead == 'm') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(53);
      END_STATE();
    case 54:
      if (lookahead == 'n') ADVANCE(69);
      END_STATE();
    case 55:
      if (lookahead == 'n') ADVANCE(79);
      END_STATE();
    case 56:
      if (lookahead == 'o') ADVANCE(41);
      END_STATE();
    case 57:
      if (lookahead == 'o') ADVANCE(55);
      END_STATE();
    case 58:
      if (lookahead == 'p') ADVANCE(75);
      END_STATE();
    case 59:
      if (lookahead == 'q') ADVANCE(81);
      END_STATE();
    case 60:
      if (lookahead == 'r') ADVANCE(50);
      END_STATE();
    case 61:
      if (lookahead == 'r') ADVANCE(74);
      END_STATE();
    case 62:
      if (lookahead == 'r') ADVANCE(65);
      END_STATE();
    case 63:
      if (lookahead == 'r') ADVANCE(67);
      END_STATE();
    case 64:
      if (lookahead == 's') ADVANCE(112);
      END_STATE();
    case 65:
      if (lookahead == 's') ADVANCE(99);
      END_STATE();
    case 66:
      if (lookahead == 's') ADVANCE(107);
      END_STATE();
    case 67:
      if (lookahead == 's') ADVANCE(102);
      END_STATE();
    case 68:
      if (lookahead == 's') ADVANCE(109);
      END_STATE();
    case 69:
      if (lookahead == 's') ADVANCE(108);
      END_STATE();
    case 70:
      if (lookahead == 's') ADVANCE(71);
      END_STATE();
    case 71:
      if (lookahead == 's') ADVANCE(45);
      END_STATE();
    case 72:
      if (lookahead == 's') ADVANCE(80);
      END_STATE();
    case 73:
      if (lookahead == 's') ADVANCE(76);
      END_STATE();
    case 74:
      if (lookahead == 't') ADVANCE(104);
      END_STATE();
    case 75:
      if (lookahead == 't') ADVANCE(105);
      END_STATE();
    case 76:
      if (lookahead == 't') ADVANCE(100);
      END_STATE();
    case 77:
      if (lookahead == 't') ADVANCE(40);
      END_STATE();
    case 78:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 79:
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 80:
      if (lookahead == 't') ADVANCE(66);
      END_STATE();
    case 81:
      if (lookahead == 'u') ADVANCE(46);
      END_STATE();
    case 82:
      if (lookahead == 'x') ADVANCE(52);
      END_STATE();
    case 83:
      if (lookahead == 'y') ADVANCE(103);
      END_STATE();
    case 84:
      if (lookahead == '{') ADVANCE(204);
      END_STATE();
    case 85:
      if (lookahead == '}') ADVANCE(207);
      END_STATE();
    case 86:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 87:
      if (eof) ADVANCE(89);
      ADVANCE_MAP(
        '\n', 90,
        '\r', 1,
        '"', 190,
        '#', 92,
        'D', 152,
        'G', 153,
        'H', 154,
        'O', 169,
        'P', 143,
        '[', 96,
        '{', 84,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(87);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(187);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(188);
      END_STATE();
    case 88:
      if (eof) ADVANCE(89);
      ADVANCE_MAP(
        '\n', 90,
        '\r', 1,
        '"', 4,
        '#', 91,
        ',', 203,
        'D', 148,
        'G', 149,
        'H', 150,
        'O', 168,
        'P', 142,
        '[', 95,
        ']', 98,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(88);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(186);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(aux_sym_newline_token1);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '{') ADVANCE(188);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(94);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(94);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '{') ADVANCE(188);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_meta);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_vars);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_request);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_headers);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_body);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_assert);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_script);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_exists);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_contains);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_matches);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_duration_value);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_duration_value);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(118);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_raw_value);
      if (lookahead == '"') ADVANCE(191);
      if (lookahead == '{') ADVANCE(117);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(114);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(115);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(118);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_raw_value);
      if (lookahead == 'm') ADVANCE(116);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(115);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(118);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_raw_value);
      if (lookahead == 's') ADVANCE(113);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(118);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_raw_value);
      if (lookahead == '{') ADVANCE(205);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(118);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_raw_value);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(118);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_GET);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_GET);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(186);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_GET);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(188);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(anon_sym_POST);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_POST);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(186);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(anon_sym_POST);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(188);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(anon_sym_PUT);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_PUT);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(186);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(anon_sym_PUT);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(188);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(anon_sym_PATCH);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(anon_sym_PATCH);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(186);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(anon_sym_PATCH);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(188);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(anon_sym_DELETE);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(anon_sym_DELETE);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(186);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(anon_sym_DELETE);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(188);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(anon_sym_HEAD);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(anon_sym_HEAD);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(186);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(anon_sym_HEAD);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(188);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(anon_sym_OPTIONS);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(anon_sym_OPTIONS);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(186);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(anon_sym_OPTIONS);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(188);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'A') ADVANCE(146);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(186);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'A') ADVANCE(147);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(188);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'A') ADVANCE(176);
      if (lookahead == 'O') ADVANCE(172);
      if (lookahead == 'U') ADVANCE(177);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(186);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'A') ADVANCE(181);
      if (lookahead == 'O') ADVANCE(173);
      if (lookahead == 'U') ADVANCE(182);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(188);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'C') ADVANCE(158);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(186);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'C') ADVANCE(159);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(188);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'D') ADVANCE(135);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(186);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'D') ADVANCE(136);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(188);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'E') ADVANCE(162);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(186);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'E') ADVANCE(174);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(186);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'E') ADVANCE(140);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(186);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'E') ADVANCE(132);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(186);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'E') ADVANCE(163);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(188);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'E') ADVANCE(179);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(188);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'E') ADVANCE(141);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(188);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'E') ADVANCE(133);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(188);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'E') ADVANCE(184);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(186);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'E') ADVANCE(185);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(188);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'H') ADVANCE(129);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(186);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'H') ADVANCE(130);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(188);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'I') ADVANCE(166);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(186);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'I') ADVANCE(167);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(188);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'L') ADVANCE(156);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(186);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'L') ADVANCE(157);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(188);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'N') ADVANCE(170);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(186);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'N') ADVANCE(171);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(188);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'O') ADVANCE(164);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(186);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'O') ADVANCE(165);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(188);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'P') ADVANCE(175);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(186);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'P') ADVANCE(180);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(188);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'S') ADVANCE(138);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(186);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'S') ADVANCE(139);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(188);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'S') ADVANCE(178);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(186);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'S') ADVANCE(183);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(188);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'T') ADVANCE(120);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(186);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'T') ADVANCE(160);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(186);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'T') ADVANCE(144);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(186);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'T') ADVANCE(126);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(186);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'T') ADVANCE(123);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(186);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'T') ADVANCE(121);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(188);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'T') ADVANCE(161);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(188);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'T') ADVANCE(145);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(188);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'T') ADVANCE(127);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(188);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'T') ADVANCE(124);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(188);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'T') ADVANCE(151);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(186);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'T') ADVANCE(155);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(188);
      END_STATE();
    case 186:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(186);
      END_STATE();
    case 187:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(188);
      END_STATE();
    case 188:
      ACCEPT_TOKEN(sym_text_fragment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '{') ADVANCE(188);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 190:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      if (lookahead == '"') ADVANCE(5);
      END_STATE();
    case 191:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(118);
      END_STATE();
    case 192:
      ACCEPT_TOKEN(sym_string_content);
      END_STATE();
    case 193:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '\\') ADVANCE(86);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(193);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(194);
      END_STATE();
    case 194:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(194);
      END_STATE();
    case 195:
      ACCEPT_TOKEN(anon_sym_DQUOTE_DQUOTE_DQUOTE);
      END_STATE();
    case 196:
      ACCEPT_TOKEN(anon_sym_DQUOTE_DQUOTE_DQUOTE);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(202);
      END_STATE();
    case 197:
      ACCEPT_TOKEN(sym_body_text);
      END_STATE();
    case 198:
      ACCEPT_TOKEN(sym_body_text);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '"') ADVANCE(200);
      if (lookahead == '{') ADVANCE(201);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(198);
      if (lookahead == '\n' ||
          lookahead == '}') ADVANCE(197);
      if (lookahead != 0) ADVANCE(202);
      END_STATE();
    case 199:
      ACCEPT_TOKEN(sym_body_text);
      if (lookahead == '"') ADVANCE(196);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(202);
      END_STATE();
    case 200:
      ACCEPT_TOKEN(sym_body_text);
      if (lookahead == '"') ADVANCE(199);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(202);
      END_STATE();
    case 201:
      ACCEPT_TOKEN(sym_body_text);
      if (lookahead == '{') ADVANCE(204);
      END_STATE();
    case 202:
      ACCEPT_TOKEN(sym_body_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(202);
      END_STATE();
    case 203:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 204:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      END_STATE();
    case 205:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(118);
      END_STATE();
    case 206:
      ACCEPT_TOKEN(aux_sym_variable_ref_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(206);
      END_STATE();
    case 207:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 88},
  [2] = {.lex_state = 88},
  [3] = {.lex_state = 88},
  [4] = {.lex_state = 87},
  [5] = {.lex_state = 87},
  [6] = {.lex_state = 87},
  [7] = {.lex_state = 87},
  [8] = {.lex_state = 87},
  [9] = {.lex_state = 88},
  [10] = {.lex_state = 88},
  [11] = {.lex_state = 88},
  [12] = {.lex_state = 88},
  [13] = {.lex_state = 88},
  [14] = {.lex_state = 88},
  [15] = {.lex_state = 88},
  [16] = {.lex_state = 88},
  [17] = {.lex_state = 88},
  [18] = {.lex_state = 88},
  [19] = {.lex_state = 88},
  [20] = {.lex_state = 88},
  [21] = {.lex_state = 88},
  [22] = {.lex_state = 88},
  [23] = {.lex_state = 88},
  [24] = {.lex_state = 88},
  [25] = {.lex_state = 88},
  [26] = {.lex_state = 88},
  [27] = {.lex_state = 88},
  [28] = {.lex_state = 88},
  [29] = {.lex_state = 6},
  [30] = {.lex_state = 9},
  [31] = {.lex_state = 10},
  [32] = {.lex_state = 10},
  [33] = {.lex_state = 10},
  [34] = {.lex_state = 10},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 7},
  [39] = {.lex_state = 7},
  [40] = {.lex_state = 7},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 7},
  [44] = {.lex_state = 7},
  [45] = {.lex_state = 8},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 9},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 7},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 6},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 8},
  [61] = {.lex_state = 93},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 8},
  [68] = {.lex_state = 8},
  [69] = {.lex_state = 8},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_newline_token1] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_meta] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_vars] = ACTIONS(1),
    [anon_sym_request] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_headers] = ACTIONS(1),
    [anon_sym_body] = ACTIONS(1),
    [anon_sym_assert] = ACTIONS(1),
    [anon_sym_script] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_exists] = ACTIONS(1),
    [anon_sym_contains] = ACTIONS(1),
    [anon_sym_matches] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym_duration_value] = ACTIONS(1),
    [anon_sym_GET] = ACTIONS(1),
    [anon_sym_POST] = ACTIONS(1),
    [anon_sym_PUT] = ACTIONS(1),
    [anon_sym_PATCH] = ACTIONS(1),
    [anon_sym_DELETE] = ACTIONS(1),
    [anon_sym_HEAD] = ACTIONS(1),
    [anon_sym_OPTIONS] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE_DQUOTE_DQUOTE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(58),
    [sym_newline] = STATE(3),
    [sym_comment] = STATE(3),
    [sym_shorthand_request] = STATE(3),
    [sym_section_header] = STATE(3),
    [sym_pair] = STATE(3),
    [sym_assertion_exists] = STATE(3),
    [sym_assertion_contains] = STATE(3),
    [sym_assertion_matches] = STATE(3),
    [sym_assertion_lt] = STATE(3),
    [sym_assertion_gt] = STATE(3),
    [sym_http_method] = STATE(30),
    [sym_triple_quoted_string] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_newline_token1] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_GET] = ACTIONS(11),
    [anon_sym_POST] = ACTIONS(11),
    [anon_sym_PUT] = ACTIONS(11),
    [anon_sym_PATCH] = ACTIONS(11),
    [anon_sym_DELETE] = ACTIONS(11),
    [anon_sym_HEAD] = ACTIONS(11),
    [anon_sym_OPTIONS] = ACTIONS(11),
    [sym_key] = ACTIONS(13),
    [anon_sym_DQUOTE_DQUOTE_DQUOTE] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      aux_sym_newline_token1,
    ACTIONS(22), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(31), 1,
      sym_key,
    ACTIONS(34), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(30), 1,
      sym_http_method,
    ACTIONS(28), 7,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
    STATE(2), 12,
      sym_newline,
      sym_comment,
      sym_shorthand_request,
      sym_section_header,
      sym_pair,
      sym_assertion_exists,
      sym_assertion_contains,
      sym_assertion_matches,
      sym_assertion_lt,
      sym_assertion_gt,
      sym_triple_quoted_string,
      aux_sym_source_file_repeat1,
  [45] = 9,
    ACTIONS(5), 1,
      aux_sym_newline_token1,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_key,
    ACTIONS(15), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    STATE(30), 1,
      sym_http_method,
    ACTIONS(11), 7,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
    STATE(2), 12,
      sym_newline,
      sym_comment,
      sym_shorthand_request,
      sym_section_header,
      sym_pair,
      sym_assertion_exists,
      sym_assertion_contains,
      sym_assertion_matches,
      sym_assertion_lt,
      sym_assertion_gt,
      sym_triple_quoted_string,
      aux_sym_source_file_repeat1,
  [90] = 6,
    ACTIONS(43), 1,
      sym_text_fragment,
    ACTIONS(45), 1,
      anon_sym_DQUOTE,
    ACTIONS(47), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(39), 3,
      ts_builtin_sym_end,
      aux_sym_newline_token1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(5), 3,
      sym_quoted_string,
      sym_variable_ref,
      aux_sym_value_repeat1,
    ACTIONS(41), 10,
      anon_sym_POUND,
      anon_sym_LBRACK,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      sym_key,
  [122] = 6,
    ACTIONS(53), 1,
      sym_text_fragment,
    ACTIONS(56), 1,
      anon_sym_DQUOTE,
    ACTIONS(59), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(49), 3,
      ts_builtin_sym_end,
      aux_sym_newline_token1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(5), 3,
      sym_quoted_string,
      sym_variable_ref,
      aux_sym_value_repeat1,
    ACTIONS(51), 10,
      anon_sym_POUND,
      anon_sym_LBRACK,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      sym_key,
  [154] = 2,
    ACTIONS(62), 4,
      ts_builtin_sym_end,
      aux_sym_newline_token1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(64), 12,
      anon_sym_POUND,
      anon_sym_LBRACK,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      sym_key,
      sym_text_fragment,
      anon_sym_DQUOTE,
  [175] = 2,
    ACTIONS(66), 4,
      ts_builtin_sym_end,
      aux_sym_newline_token1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(68), 12,
      anon_sym_POUND,
      anon_sym_LBRACK,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      sym_key,
      sym_text_fragment,
      anon_sym_DQUOTE,
  [196] = 2,
    ACTIONS(70), 4,
      ts_builtin_sym_end,
      aux_sym_newline_token1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(72), 12,
      anon_sym_POUND,
      anon_sym_LBRACK,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      sym_key,
      sym_text_fragment,
      anon_sym_DQUOTE,
  [217] = 2,
    ACTIONS(66), 7,
      ts_builtin_sym_end,
      aux_sym_newline_token1,
      anon_sym_POUND,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_COMMA,
    ACTIONS(68), 8,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      sym_key,
  [237] = 2,
    ACTIONS(62), 7,
      ts_builtin_sym_end,
      aux_sym_newline_token1,
      anon_sym_POUND,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_COMMA,
    ACTIONS(64), 8,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      sym_key,
  [257] = 2,
    ACTIONS(74), 5,
      ts_builtin_sym_end,
      aux_sym_newline_token1,
      anon_sym_POUND,
      anon_sym_LBRACK,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(76), 8,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      sym_key,
  [275] = 2,
    ACTIONS(78), 5,
      ts_builtin_sym_end,
      aux_sym_newline_token1,
      anon_sym_POUND,
      anon_sym_LBRACK,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(80), 8,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      sym_key,
  [293] = 2,
    ACTIONS(82), 5,
      ts_builtin_sym_end,
      aux_sym_newline_token1,
      anon_sym_POUND,
      anon_sym_LBRACK,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(84), 8,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      sym_key,
  [311] = 2,
    ACTIONS(86), 5,
      ts_builtin_sym_end,
      aux_sym_newline_token1,
      anon_sym_POUND,
      anon_sym_LBRACK,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(88), 8,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      sym_key,
  [329] = 2,
    ACTIONS(90), 5,
      ts_builtin_sym_end,
      aux_sym_newline_token1,
      anon_sym_POUND,
      anon_sym_LBRACK,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(92), 8,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      sym_key,
  [347] = 2,
    ACTIONS(94), 5,
      ts_builtin_sym_end,
      aux_sym_newline_token1,
      anon_sym_POUND,
      anon_sym_LBRACK,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(96), 8,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      sym_key,
  [365] = 2,
    ACTIONS(98), 5,
      ts_builtin_sym_end,
      aux_sym_newline_token1,
      anon_sym_POUND,
      anon_sym_LBRACK,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(100), 8,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      sym_key,
  [383] = 2,
    ACTIONS(102), 5,
      ts_builtin_sym_end,
      aux_sym_newline_token1,
      anon_sym_POUND,
      anon_sym_LBRACK,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(104), 8,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      sym_key,
  [401] = 2,
    ACTIONS(106), 5,
      ts_builtin_sym_end,
      aux_sym_newline_token1,
      anon_sym_POUND,
      anon_sym_LBRACK,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(108), 8,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      sym_key,
  [419] = 2,
    ACTIONS(110), 5,
      ts_builtin_sym_end,
      aux_sym_newline_token1,
      anon_sym_POUND,
      anon_sym_LBRACK,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(112), 8,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      sym_key,
  [437] = 2,
    ACTIONS(114), 5,
      ts_builtin_sym_end,
      aux_sym_newline_token1,
      anon_sym_POUND,
      anon_sym_LBRACK,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(116), 8,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      sym_key,
  [455] = 2,
    ACTIONS(118), 5,
      ts_builtin_sym_end,
      aux_sym_newline_token1,
      anon_sym_POUND,
      anon_sym_LBRACK,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(120), 8,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      sym_key,
  [473] = 2,
    ACTIONS(122), 5,
      ts_builtin_sym_end,
      aux_sym_newline_token1,
      anon_sym_POUND,
      anon_sym_LBRACK,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(124), 8,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      sym_key,
  [491] = 2,
    ACTIONS(126), 5,
      ts_builtin_sym_end,
      aux_sym_newline_token1,
      anon_sym_POUND,
      anon_sym_LBRACK,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(128), 8,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      sym_key,
  [509] = 2,
    ACTIONS(130), 5,
      ts_builtin_sym_end,
      aux_sym_newline_token1,
      anon_sym_POUND,
      anon_sym_LBRACK,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(132), 8,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      sym_key,
  [527] = 2,
    ACTIONS(134), 5,
      ts_builtin_sym_end,
      aux_sym_newline_token1,
      anon_sym_POUND,
      anon_sym_LBRACK,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(136), 8,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      sym_key,
  [545] = 2,
    ACTIONS(70), 5,
      ts_builtin_sym_end,
      aux_sym_newline_token1,
      anon_sym_POUND,
      anon_sym_LBRACK,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(72), 8,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      sym_key,
  [563] = 2,
    ACTIONS(138), 5,
      ts_builtin_sym_end,
      aux_sym_newline_token1,
      anon_sym_POUND,
      anon_sym_LBRACK,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(140), 8,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      sym_key,
  [581] = 6,
    ACTIONS(47), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(142), 1,
      anon_sym_LBRACK,
    ACTIONS(144), 1,
      sym_text_fragment,
    ACTIONS(146), 1,
      anon_sym_DQUOTE,
    STATE(15), 2,
      sym_value,
      sym_array_value,
    STATE(4), 3,
      sym_quoted_string,
      sym_variable_ref,
      aux_sym_value_repeat1,
  [603] = 5,
    ACTIONS(47), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(146), 1,
      anon_sym_DQUOTE,
    ACTIONS(148), 1,
      sym_text_fragment,
    STATE(14), 1,
      sym_value,
    STATE(4), 3,
      sym_quoted_string,
      sym_variable_ref,
      aux_sym_value_repeat1,
  [621] = 5,
    ACTIONS(152), 1,
      anon_sym_DQUOTE,
    ACTIONS(154), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(16), 1,
      sym_assertion_value,
    ACTIONS(150), 2,
      sym_duration_value,
      sym_raw_value,
    STATE(11), 2,
      sym_quoted_string,
      sym_variable_ref,
  [639] = 5,
    ACTIONS(152), 1,
      anon_sym_DQUOTE,
    ACTIONS(154), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(19), 1,
      sym_assertion_value,
    ACTIONS(150), 2,
      sym_duration_value,
      sym_raw_value,
    STATE(11), 2,
      sym_quoted_string,
      sym_variable_ref,
  [657] = 5,
    ACTIONS(152), 1,
      anon_sym_DQUOTE,
    ACTIONS(154), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(18), 1,
      sym_assertion_value,
    ACTIONS(150), 2,
      sym_duration_value,
      sym_raw_value,
    STATE(11), 2,
      sym_quoted_string,
      sym_variable_ref,
  [675] = 5,
    ACTIONS(152), 1,
      anon_sym_DQUOTE,
    ACTIONS(154), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(20), 1,
      sym_assertion_value,
    ACTIONS(150), 2,
      sym_duration_value,
      sym_raw_value,
    STATE(11), 2,
      sym_quoted_string,
      sym_variable_ref,
  [693] = 5,
    ACTIONS(156), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(158), 1,
      sym_body_text,
    ACTIONS(160), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(62), 1,
      sym_body_content,
    STATE(42), 2,
      sym_variable_ref,
      aux_sym_body_content_repeat1,
  [710] = 6,
    ACTIONS(162), 1,
      anon_sym_EQ,
    ACTIONS(164), 1,
      anon_sym_exists,
    ACTIONS(166), 1,
      anon_sym_contains,
    ACTIONS(168), 1,
      anon_sym_matches,
    ACTIONS(170), 1,
      anon_sym_LT,
    ACTIONS(172), 1,
      anon_sym_GT,
  [729] = 2,
    ACTIONS(176), 1,
      anon_sym_request,
    ACTIONS(174), 4,
      anon_sym_meta,
      anon_sym_vars,
      anon_sym_assert,
      anon_sym_script,
  [739] = 4,
    ACTIONS(178), 1,
      anon_sym_DQUOTE,
    ACTIONS(180), 1,
      sym_string_content,
    ACTIONS(182), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(39), 2,
      sym_variable_ref,
      aux_sym_quoted_string_repeat1,
  [753] = 4,
    ACTIONS(182), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(184), 1,
      anon_sym_DQUOTE,
    ACTIONS(186), 1,
      sym_string_content,
    STATE(40), 2,
      sym_variable_ref,
      aux_sym_quoted_string_repeat1,
  [767] = 4,
    ACTIONS(188), 1,
      anon_sym_DQUOTE,
    ACTIONS(190), 1,
      sym_string_content,
    ACTIONS(193), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(40), 2,
      sym_variable_ref,
      aux_sym_quoted_string_repeat1,
  [781] = 4,
    ACTIONS(196), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(198), 1,
      sym_body_text,
    ACTIONS(201), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(41), 2,
      sym_variable_ref,
      aux_sym_body_content_repeat1,
  [795] = 4,
    ACTIONS(160), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(204), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(206), 1,
      sym_body_text,
    STATE(41), 2,
      sym_variable_ref,
      aux_sym_body_content_repeat1,
  [809] = 4,
    ACTIONS(182), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(208), 1,
      anon_sym_DQUOTE,
    ACTIONS(210), 1,
      sym_string_content,
    STATE(44), 2,
      sym_variable_ref,
      aux_sym_quoted_string_repeat1,
  [823] = 4,
    ACTIONS(182), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(186), 1,
      sym_string_content,
    ACTIONS(212), 1,
      anon_sym_DQUOTE,
    STATE(40), 2,
      sym_variable_ref,
      aux_sym_quoted_string_repeat1,
  [837] = 3,
    ACTIONS(214), 1,
      anon_sym_RBRACK,
    ACTIONS(216), 1,
      anon_sym_DQUOTE,
    STATE(46), 1,
      sym_quoted_string,
  [847] = 3,
    ACTIONS(218), 1,
      anon_sym_RBRACK,
    ACTIONS(220), 1,
      anon_sym_COMMA,
    STATE(48), 1,
      aux_sym_array_value_repeat1,
  [857] = 1,
    ACTIONS(222), 3,
      sym_text_fragment,
      anon_sym_DQUOTE,
      anon_sym_LBRACE_LBRACE,
  [863] = 3,
    ACTIONS(220), 1,
      anon_sym_COMMA,
    ACTIONS(224), 1,
      anon_sym_RBRACK,
    STATE(50), 1,
      aux_sym_array_value_repeat1,
  [873] = 2,
    ACTIONS(70), 1,
      sym_string_content,
    ACTIONS(72), 2,
      anon_sym_DQUOTE,
      anon_sym_LBRACE_LBRACE,
  [881] = 3,
    ACTIONS(226), 1,
      anon_sym_RBRACK,
    ACTIONS(228), 1,
      anon_sym_COMMA,
    STATE(50), 1,
      aux_sym_array_value_repeat1,
  [891] = 1,
    ACTIONS(72), 3,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      sym_body_text,
      anon_sym_LBRACE_LBRACE,
  [897] = 1,
    ACTIONS(231), 2,
      anon_sym_headers,
      anon_sym_body,
  [902] = 2,
    ACTIONS(233), 1,
      anon_sym_RBRACK,
    ACTIONS(235), 1,
      anon_sym_DOT,
  [909] = 2,
    ACTIONS(216), 1,
      anon_sym_DQUOTE,
    STATE(55), 1,
      sym_quoted_string,
  [916] = 1,
    ACTIONS(226), 2,
      anon_sym_RBRACK,
      anon_sym_COMMA,
  [921] = 1,
    ACTIONS(233), 1,
      anon_sym_RBRACK,
  [925] = 1,
    ACTIONS(237), 1,
      anon_sym_RBRACE_RBRACE,
  [929] = 1,
    ACTIONS(239), 1,
      ts_builtin_sym_end,
  [933] = 1,
    ACTIONS(241), 1,
      anon_sym_RBRACK,
  [937] = 1,
    ACTIONS(243), 1,
      aux_sym_variable_ref_token1,
  [941] = 1,
    ACTIONS(245), 1,
      aux_sym_comment_token1,
  [945] = 1,
    ACTIONS(247), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
  [949] = 1,
    ACTIONS(249), 1,
      aux_sym_newline_token1,
  [953] = 1,
    ACTIONS(251), 1,
      anon_sym_RBRACE_RBRACE,
  [957] = 1,
    ACTIONS(253), 1,
      anon_sym_RBRACE_RBRACE,
  [961] = 1,
    ACTIONS(255), 1,
      anon_sym_RBRACE_RBRACE,
  [965] = 1,
    ACTIONS(257), 1,
      aux_sym_variable_ref_token1,
  [969] = 1,
    ACTIONS(259), 1,
      aux_sym_variable_ref_token1,
  [973] = 1,
    ACTIONS(261), 1,
      aux_sym_variable_ref_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 45,
  [SMALL_STATE(4)] = 90,
  [SMALL_STATE(5)] = 122,
  [SMALL_STATE(6)] = 154,
  [SMALL_STATE(7)] = 175,
  [SMALL_STATE(8)] = 196,
  [SMALL_STATE(9)] = 217,
  [SMALL_STATE(10)] = 237,
  [SMALL_STATE(11)] = 257,
  [SMALL_STATE(12)] = 275,
  [SMALL_STATE(13)] = 293,
  [SMALL_STATE(14)] = 311,
  [SMALL_STATE(15)] = 329,
  [SMALL_STATE(16)] = 347,
  [SMALL_STATE(17)] = 365,
  [SMALL_STATE(18)] = 383,
  [SMALL_STATE(19)] = 401,
  [SMALL_STATE(20)] = 419,
  [SMALL_STATE(21)] = 437,
  [SMALL_STATE(22)] = 455,
  [SMALL_STATE(23)] = 473,
  [SMALL_STATE(24)] = 491,
  [SMALL_STATE(25)] = 509,
  [SMALL_STATE(26)] = 527,
  [SMALL_STATE(27)] = 545,
  [SMALL_STATE(28)] = 563,
  [SMALL_STATE(29)] = 581,
  [SMALL_STATE(30)] = 603,
  [SMALL_STATE(31)] = 621,
  [SMALL_STATE(32)] = 639,
  [SMALL_STATE(33)] = 657,
  [SMALL_STATE(34)] = 675,
  [SMALL_STATE(35)] = 693,
  [SMALL_STATE(36)] = 710,
  [SMALL_STATE(37)] = 729,
  [SMALL_STATE(38)] = 739,
  [SMALL_STATE(39)] = 753,
  [SMALL_STATE(40)] = 767,
  [SMALL_STATE(41)] = 781,
  [SMALL_STATE(42)] = 795,
  [SMALL_STATE(43)] = 809,
  [SMALL_STATE(44)] = 823,
  [SMALL_STATE(45)] = 837,
  [SMALL_STATE(46)] = 847,
  [SMALL_STATE(47)] = 857,
  [SMALL_STATE(48)] = 863,
  [SMALL_STATE(49)] = 873,
  [SMALL_STATE(50)] = 881,
  [SMALL_STATE(51)] = 891,
  [SMALL_STATE(52)] = 897,
  [SMALL_STATE(53)] = 902,
  [SMALL_STATE(54)] = 909,
  [SMALL_STATE(55)] = 916,
  [SMALL_STATE(56)] = 921,
  [SMALL_STATE(57)] = 925,
  [SMALL_STATE(58)] = 929,
  [SMALL_STATE(59)] = 933,
  [SMALL_STATE(60)] = 937,
  [SMALL_STATE(61)] = 941,
  [SMALL_STATE(62)] = 945,
  [SMALL_STATE(63)] = 949,
  [SMALL_STATE(64)] = 953,
  [SMALL_STATE(65)] = 957,
  [SMALL_STATE(66)] = 961,
  [SMALL_STATE(67)] = 965,
  [SMALL_STATE(68)] = 969,
  [SMALL_STATE(69)] = 973,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_string, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 3, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_string, 3, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_ref, 3, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_ref, 3, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assertion_value, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assertion_value, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_newline, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_newline, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shorthand_request, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_shorthand_request, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pair, 3, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assertion_contains, 3, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assertion_contains, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_header, 3, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_header, 3, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assertion_matches, 3, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assertion_matches, 3, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assertion_lt, 3, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assertion_lt, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assertion_gt, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assertion_gt, 3, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_triple_quoted_string, 3, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_triple_quoted_string, 3, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_value, 3, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_value, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assertion_exists, 2, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assertion_exists, 2, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_value, 2, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_value, 2, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_triple_quoted_string, 4, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_triple_quoted_string, 4, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_value, 4, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_value, 4, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_header, 5, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_header, 5, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [154] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [156] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [158] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_string_repeat1, 2, 0, 0),
  [190] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_string_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [193] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_string_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_body_content_repeat1, 2, 0, 0),
  [198] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_content_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [201] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_content_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body_content, 1, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [208] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [212] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_http_method, 1, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_value_repeat1, 2, 0, 0),
  [228] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_value_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [239] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_nap(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "nap",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
