#!/usr/bin/env bash
set -euo pipefail

# Regenerate the gitignored src/Napper.Core/Types.Generated.fs from the canonical
# Types.td (typeDiagram DSL). Cross-platform: runs under bash on Linux, macOS, AND
# Windows (git-bash) so every release runner can produce it before the F# build —
# unlike `make generate-types`, whose recipe uses Unix `printf` and fails under the
# Makefile's PowerShell shell on Windows. Requires `typediagram` on PATH.
# Canonical source of truth: src/Napper.Core/Types.td. See Nimblesite/typeDiagram#36.

command -v typediagram >/dev/null 2>&1 || {
  echo "ERROR: typediagram not on PATH (install with: npm install -g typediagram)" >&2
  exit 1
}

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TD="${ROOT}/src/Napper.Core/Types.td"
GEN="${ROOT}/src/Napper.Core/Types.Generated.fs"

{
  printf '%s\n' \
    '// <auto-generated> DO NOT EDIT. Rebuilt by: make generate-types' \
    '// Canonical source of truth: src/Napper.Core/Types.td (typeDiagram DSL).' \
    '// See https://github.com/Nimblesite/typeDiagram/issues/36' \
    '' \
    'namespace Napper.Core' \
    '' \
    '// Host-type bridge: the typeDiagram opaque type Duration maps to BCL TimeSpan.' \
    'type Duration = System.TimeSpan' \
    ''
  typediagram --to fsharp "${TD}"
} >"${GEN}"

echo "==> Generated ${GEN} from ${TD}"
